language: node_js
node_js:
- "10"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- npm i
- npm run migrate
- node index.js &
- node_modules/.bin/newman run tests/API_Blog_Voyage_Tests.postman_collection.json --delay-request 20