language: node_js
node_js:
- "8.2.1"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- cd Ex2/
- npm i
- node serve.js
- node_modules/.bin/newman run tests/Tuples.postman_collection.json